homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret home_assistant_name
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_assistant_lat
  longitude: !secret home_assistant_lon
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_assistant_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret home_assistant_timezone
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Cloud
cloud:

# Enable companion app
mobile_app:

# LG tv 
webostv:
  host: !secret webos_host
  name: !secret webos_name

# Enable custom circadion lighting component
circadian_lighting:
  min_colortemp: 1000

# Switches
switch: !include_dir_list switches/

# Lights
light: !include_dir_list lights/

# Create input boolean to import in homekit
input_boolean:
  hue_motion_gang:

# Create template for the input boolean hue_motion_gang
binary_sensor:
  - platform: template
    sensors:
      hue_motion_gang:
        device_class: motion
        value_template: >-
          {{ is_state('input_boolean.hue_motion_gang', 'on') }}

# Homekit integration. Only import hue_motion_gang since I only want to use the motion sensor via homekit.
# Motion sensor via homekit is way more responsive.
homekit:
  filter:
    include_entities:
      - input_boolean.hue_motion_gang

# Automations
automation ui: !include automations.yaml
automation manual: !include_dir_list automations/
group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
