alias: "Lichten aan wanneer we thuis komen"
trigger:
  platform: state
  entity_id: group.family
  from: "not_home"
  to: "home"
condition:
  condition: state
  entity_id: sun.sun
  state: "below_horizon"
action:
  - service: switch.turn_on
    target:
      entity_id: switch.circadian_lighting_woonkamer_adaptive_lights
  - service: light.turn_on
    data:
      kelvin: "{{ state_attr('sensor.circadian_values', 'colortemp') | int }}"
      brightness_pct: "{{ state_attr('switch.circadian_lighting_woonkamer_adaptive_lights', 'brightness') | int }}"
    target:
      entity_id: light.zithoek
  - service: light.turn_on
    data:
      brightness_pct: 40
    target:
      entity_id: light.eettafel
  - service: light.turn_on
    target:
      entity_id: light.vitrinekast